version: '3.0'
services:
  peer:
    image: hyperledger/fabric-peer:2.5.0
    command: peer node start
    working_dir: /root
    hostname: ${NODE_HOST}
    networks:
      - fabric-ca
    volumes:
      - ${BASE_DIR}/${OUT_DIR}/${ROOT_TLS_CERT}:/etc/hyperledger/fabric/tls/ca.crt
      - ${BASE_DIR}/${OUT_DIR}/organizations/${ORG_TYPE}/${ORG_NAME}/nodes/${NODE_NAME}/msp:/etc/hyperledger/fabric/msp
      - ${BASE_DIR}/${OUT_DIR}/organizations/${ORG_TYPE}/${ORG_NAME}/nodes/${NODE_NAME}/tls/msp/signcerts/cert.pem:/etc/hyperledger/fabric/tls/server.crt
      - ${BASE_DIR}/${OUT_DIR}/organizations/${ORG_TYPE}/${ORG_NAME}/nodes/${NODE_NAME}/tls/msp/keystore/key.pem:/etc/hyperledger/fabric/tls/server.key
      - ${BASE_DIR}/config/config.yaml:/etc/hyperledger/fabric/msp/config.yaml
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=${ORG_NAME}:${NODE_NAME}
      - CORE_PEER_ADDRESS=${NODE_HOST}:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=${NODE_HOST}:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=${NODE_HOST}:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${NODE_HOST}:7051
      - CORE_PEER_LOCALMSPID=${ORG_NAME}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=${NODE_HOST}:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric


networks:
  fabric-ca:
