version: '3.0'
services:
  orderer-${ORG_NAME}-${NODE_NAME}:
    image: hyperledger/fabric-orderer
    command:  orderer start
    #command: ls /etc/hyperledger/fabric/msp
    working_dir: /root
    hostname: ${NODE_HOST}
    networks:
      - fabric-ca
    volumes:
      - ${BASE_DIR}/${OUT_DIR}/${ROOT_TLS_CERT}:/etc/hyperledger/fabric/tls/ca.crt
      - ${BASE_DIR}/${OUT_DIR}/organizations/${ORG_TYPE}/${ORG_NAME}/nodes/${NODE_NAME}/msp:/etc/hyperledger/fabric/msp
      - ${BASE_DIR}/${OUT_DIR}/organizations/${ORG_TYPE}/${ORG_NAME}/nodes/${NODE_NAME}/tls/msp/signcerts/cert.pem:/etc/hyperledger/fabric/tls/server.crt
      - ${BASE_DIR}/${OUT_DIR}/organizations/${ORG_TYPE}/${ORG_NAME}/nodes/${NODE_NAME}/tls/msp/keystore/key.pem:/etc/hyperledger/fabric/tls/server.key
      - ${BASE_DIR}/config/config.yaml:/etc/hyperledger/fabric/msp/config.yaml
    environment:
      - FABRIC_LOGGING_SPEC=WARNING
      - ORDERER_GENERAL_LISTENADDRESS=${NODE_HOST}
      - ORDERER_GENERAL_LISTENPORT=${NODE_PORT}
      - ORDERER_GENERAL_LOCALMSPID=${ORG_NAME}:${NODE_NAME} 
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=${NODE_HOST}:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=${NODE_HOST}:9443
      - ORDERER_METRICS_PROVIDER=prometheus

networks:
  fabric-ca: